version: "3.9"

services:

  database:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    ports:
      - "8000:80"
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "3000:5173"   # Maps Vite dev server port 5173 to host 3000
    depends_on:
      - backend